#pragma once
#define _USE_MATH_DEFINES
#include <cmath>
#include <set>
#include <map>
#include <list>
#include <queue>
#include <vector>
#include <memory>
#include <iostream>
#include <algorithm>
#include <functional>